version: '3.6'
services:
  cfssl:
    image: blackducksoftware/blackduck-cfssl:1.0.1
    volumes: ['cert-volume:/etc/cfssl']
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'http://localhost:8888/api/v1/cfssl/scaninfo']
      interval: 30s
      timeout: 10s
      retries: 5
    user: cfssl:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 640M}
        reservations: {memory: 640M}
  alert:
    image: blackducksoftware/blackduck-alert:ALERT_VERSION_TOKEN
    ports: ['8443:8443']
    env_file: [blackduck-alert.env]
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/alert/api/about',
             /opt/blackduck/alert/security/root.crt, /opt/blackduck/alert/security/blackduck_system.crt,
             /opt/blackduck/alert/security/blackduck_system.key]
      interval: 30s
      timeout: 60s
      retries: 15
      start_period: 7200s
    volumes: ['alert-db-volume:/opt/blackduck/alert/alert-config/data']
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 15s, window: 60s}
      resources:
        limits: {memory: 2560M}
        reservations: {memory: 2560M}
volumes: {cert-volume: null, alert-db-volume: null}
