version: '2.1'
services:
  cfssl:
    image: blackducksoftware/hub-cfssl:4.7.0
    volumes: ['cert-volume:/etc/cfssl']
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'http://localhost:8888/api/v1/cfssl/scaninfo']
      interval: 30s
      timeout: 10s
      retries: 5
    user: cfssl:root
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 5s, window: 60s}
      resources:
        limits: {memory: 640M}
        reservations: {memory: 640M}
  alert:
    image: blackducksoftware/blackduck-alert:VERSION_TOKEN
    ports: ['8443:8443']
    links: [cfssl]
    env_file: [blackduck-alert.env]
    user: hubalert:root
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/alert/api/about']
      interval: 30s
      timeout: 10s
      retries: 5
    volumes: ['alert-db-volume:/opt/blackduck/alert/alert-config/data', 'alert-volume:/opt/blackduck/alert/alert-config/security']
    deploy:
      mode: replicated
      restart_policy: {condition: on-failure, delay: 15s, window:60s}
      resources:
        limits: {memory: 512M}
        reservations: {memory: 512M}
volumes: {cert-volume: null, alert-db-volume: null, alert-volume: null }
