kind: List
apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: alert
    spec:
      selector:
        matchLabels:
          app: alert
          tier: alert
      replicas: 1
      template:
        metadata:
          name: alert
          labels:
            app: alert
            tier: alert
        spec:
          volumes:
            # NOTE: replace the emptyDir volume with a persistent volume or all the data will be lost when the pod is destroyed.
            - emptyDir: {}
              name: dir-alert
          containers:
            - image: blackducksoftware/alert-database:1.0.0
              name: alertdb
              livenessProbe:
                exec:
                  command:
                    - /usr/local/bin/alertdb-healthcheck.sh
                initialDelaySeconds: 240
                timeoutSeconds: 10
                periodSeconds: 30
                failureThreshold: 5
              imagePullPolicy: Always
              resources:
                requests:
                  memory: 512M
                limits:
                  memory: 512M
              envFrom:
                - configMapRef:
                    name: blackduck-alert-config
              env:
                - name: PGDATA
                  value: /opt/blackduck/alert/alert-config/data/postgres/alertdb
              volumeMounts:
                - mountPath: /opt/blackduck/alert/alert-config
                  name: dir-alert
              ports:
                - containerPort: 5432
                  protocol: TCP
            - image: blackducksoftware/blackduck-alert:VERSION_TOKEN
              name: alert
              livenessProbe:
                exec:
                  command:
                    - /usr/local/bin/docker-healthcheck.sh
                    - 'https://localhost:8443/alert/api/about'
                    - /opt/blackduck/alert/security/root.crt
                    - /opt/blackduck/alert/security/blackduck_system.crt
                    - /opt/blackduck/alert/security/blackduck_system.key
                initialDelaySeconds: 240
                timeoutSeconds: 60
                periodSeconds: 30
                failureThreshold: 15
              imagePullPolicy: Always
              resources:
                requests:
                  memory: 2560M
                limits:
                  memory: 2560M
              envFrom:
                - configMapRef:
                    name: blackduck-alert-config
              volumeMounts:
                - mountPath: /opt/blackduck/alert/alert-config
                  name: dir-alert
              ports:
                - containerPort: 8443
                  protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      name: alert
    spec:
      ports:
        - name: 8443-tcp
          protocol: TCP
          port: 8443
          targetPort: 8443
      selector:
        app: alert
      type: LoadBalancer
    status:
      loadBalancer: {}
